# Generated by Django 4.2.5 on 2023-10-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status1',
            field=models.IntegerField(default=1),
        ),
    ]
