# Generated by Django 4.2.5 on 2023-10-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_status1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='status1',
        ),
    ]
